### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/yukon#15]

**Comment by Zarkopafilis** [comment]
This was on the plans since the first conversations regarding Yukon and uavcan 1.0. 

Features would basically be everything that the vuejs app is doing (or maybe most of it). Are we going to both support one-off commands and an interactive interface @pavel-kirienko ?

Design conversation is open to everyone; the backend is made with python: it makes sense making the cli in the same language, but feel free to propose something different if you like.
